[versions]
gradle-starter = "0.91.0"
gradle-gradlepublish = "2.0.0"
gradle-doctor = "0.12.1"
google-agp = "8.13.1"
mavencentral-junit = "5.14.1"
mavencentral-assertj = "3.27.6"
mavencentral-apachecommons = "3.20.0"
mavencentral-usefulnesswebp = "0.10.2"
maven-binarycompatiblity = "0.18.1"
maven-dokka = "2.1.0"

[libraries]
agp-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "google-agp" }
agp-gradle-impl = { module = "com.android.tools.build:gradle", version.ref = "google-agp" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "mavencentral-junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "mavencentral-junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "mavencentral-assertj" }
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "mavencentral-apachecommons" }
usefulness-webp = { module = "com.github.usefulness:webp-imageio", version.ref = "mavencentral-usefulnesswebp" }
jetbrains-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "maven-dokka" }

[plugins]
gradle-publishplugin = { id = "com.gradle.plugin-publish", version.ref = "gradle-gradlepublish" }
starter-config = { id = "com.starter.config", version.ref = "gradle-starter" }
starter-versioning = { id = "com.starter.versioning", version.ref = "gradle-starter" }
starter-library-kotlin = { id = "com.starter.library.kotlin", version.ref = "gradle-starter" }
osacky-doctor = { id = "com.osacky.doctor", version.ref = "gradle-doctor" }
kotlinx-binarycompatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "maven-binarycompatiblity" }
