[versions]
gradle-starter = "0.50.0"
gradle-kotlinter = "3.11.1"
gradle-gradlepublish = "1.0.0"
google-agp = "7.2.2"
gradle-jacocotestkit = "1.0.9"
mavencentral-kotlin = "1.7.10"
mavencentral-issuechecker = "0.3.0"
mavencentral-junit = "5.9.0"
mavencentral-assertj = "3.23.1"
mavencentral-apachecommons="3.12.0"
mavencentral-usefulnesswebp="0.2.1"

[libraries]
starter-gradle = { module = "com.project.starter:android", version.ref = "gradle-starter" }
agp-gradle = { module = "com.android.tools.build:gradle", version.ref = "google-agp" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "mavencentral-kotlin" }
jmailen-kotlinter = { module = "org.jmailen.gradle:kotlinter-gradle", version.ref = "gradle-kotlinter" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "mavencentral-junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "mavencentral-junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "mavencentral-assertj" }
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "mavencentral-apachecommons" }
usefulness-webp = { module = "com.github.usefulness:webp-imageio", version.ref = "mavencentral-usefulnesswebp" }

[plugins]
jmailen-kotlinter = { id = "org.jmailen.kotlinter", version.ref = "gradle-kotlinter" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "mavencentral-kotlin" }
gradle-publishplugin = { id = "com.gradle.plugin-publish", version.ref = "gradle-gradlepublish" }
droidsonroids-jacocotestkit = { id = "pl.droidsonroids.jacoco.testkit", version.ref = "gradle-jacocotestkit" }
